spring:
  application:
    name: ms-checkout
  zipkin:
    base-url: http://localhost:9411
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/waliki
    username: mysql
    password: mysql
  data:
    rest:
      base-path: /api
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: ${SERVER_PORT:9092}

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    leaseRenewalIntervalInSeconds: 4
    leaseExpirationDurationInSeconds: 8


